name: My First Workflow

on:
  push:

jobs:
  hello-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello
        run: echo "Hello DevOps!"

      - name: Print Date
        run: date

      - name: Print Current Directory
        run: pwd

      - name: Print name
        run: echo "Venkatesh"

      - name: Display content
        run: ls -ls

      - name: Git version
        run: Git version
