name: My First Workflow

on:
  push:

jobs:
  hello-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello
        run: echo "Hello DevOps!"

      - name: Print Date
        run: date

      - name: Print Current Directory
        run: pwd
